% MATLAB Publish Configurations
% @version 1
% It is recommended that you do not edit this file directly, but use the
% Configuration Editor provided in MATLAB. Changes made to comments that
% exist outside of a configuration will not be saved.

%% @name Factory Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

%% @name User Default

publish_options.outputFileFormat='html';
publish_options.outputLocation='';
publish_options.styleSheet='';
publish_options.figureCaptureMethod='entireGUIWindow';
publish_options.imageFormat='default';
publish_options.useNewFigure=true;
publish_options.maxWidth=Inf;
publish_options.maxHeight=Inf;
publish_options.showCode=true;
publish_options.evaluateCode=true;
publish_options.catchError=true;
publish_options.createThumbnail=true;
publish_options.maxNumberOfOutputLines=Inf;

